### ISSUE TITLE
Moving Graphql into server side causes errors

### ISSUE THREAD

**Issue by cskiwi** [cyco130/vavite#103]
Hi,

I'm not fully sure this is a vavite's issue, but I have to start somewhere.
Given the following template: https://github.com/cskiwi/angular-nestjs-vite

If you'd move the `GraphQLModule` from `src/app/main.ts` to the shared (between SSR and Client render): `src/shared.module.ts` you get the following error at build:

```
x Build failed in 38.20s
error during build:
Error: Unexpected early exit. This happens when Promises returned by plugins cannot resolve. Unfinished hook action(s) on exit:
(vite:esbuild) transform "C:/Users/<path>/angular-nestjs-vite/libs/frontend/modules/graphql/src/graphql.module.ts"
(vite:esbuild) transform "C:\\Users\\<path>\angular-nestjs-vite\\libs\\frontend\\modules\\graphql\\src\\index.ts"
    at process.handleBeforeExit (file:///C:/Users/<path>/angular-nestjs-vite/node_modules/rollup/dist/es/shared/node-entry.js:19932:28)      
    at Object.onceWrapper (node:events:634:26)
    at process.emit (node:events:519:28)
Warning: command "vite build && vite build --ssr --sourcemap false --mode production" exited with non-zero status code
```

any suggestions on what might be going wrong (or even better how to fix it) would greatly be appreciated

**Comment by cskiwi** [comment]
Ok, I found some stuff and now I have the following error:

```log
vavite/reloader: Failed to load server entry
SyntaxError: [vite] Named export 'ApolloLink' not found. The requested module '@apollo/client/core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@apollo/client/core';
const {ApolloLink} = pkg;

    at analyzeImportedModDifference (file:///C:/<path>/node_modules/vite/dist/node/runtime.js:514:13)
    at ViteRuntime.processImport (file:///C:/<path>/node_modules/vite/dist/node/runtime.js:894:66)
    at ViteRuntime.cachedRequest (file:///<path>/node_modules/vite/dist/node/runtime.js:912:21)
```

however when I build the project and then run the project with `node <path>/server/index.js` it works. So it's something that's only happening at `serve` time

I tried lot's of thinge, but none worked:
- adding `    "esModuleInterop": true,` to my tsconfig 
- changing `moduleResolution` to `budler`
- using `vite-plugin-cjs-interop`
- ....

other suggestions are most welcome!
