### ISSUE TITLE
Fastify + VPS example is not working

### ISSUE THREAD

**Issue by cyco130** [cyco130/vavite#45]
[It fails](https://stackblitz.com/github/cyco130/vavite/tree/main/examples/fastify-vite-plugin-ssr) with the following error:

```
TypeError: Cannot read properties of undefined (reading 'server')
    at Module.handler [as default] (/home/projects/aonimpwnl.github/server/index.ts:47:11)
    at async eval (file://file:///home/projects/aonimpwnl.github/node_modules/@vavite/connect/dist/index.mjs:82:15)
```

**Comment by cyco130** [comment]
Fixed. You may need to wait until StackBlitz invalidates its cache or you can check https://stackblitz.com/github/cyco130/vavite/tree/fix/fastify-vps-example/examples/fastify-vite-plugin-ssr until then.
